version: 2.1
orbs:
    snyk: snyk/snyk@0.0.8
jobs:
    build-test-monitor:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install
            - run: npm test
            - snyk/scan:
                fail-on-issues: true
                monitor-on-build: true
                token-variable: SNYK_TOKEN
            - run: npx semantic-release
            # - run: npm run pkg-binaries && cp package.json dist/
            # - persist_to_workspace:
            #     root: .
            #     paths:
            #       - dist/*
    build-test:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install
            - run: npm test
            - snyk/scan:
                fail-on-issues: true
                monitor-on-build: false
                token-variable: SNYK_TOKEN
                additional-arguments: --json-file-output=snykTestResults.json
            - run: ./snyk-prevent-gh-commit-status-linux ./snykTestResults.json ${GITHUB_TOKEN} ${CIRCLE_PROJECT_USERNAME} ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_SHA1} ${CIRCLE_PULL_REQUEST} ${CIRCLE_BUILD_URL}
            - run: npx tsc
    build-test-from-fork:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install
            - run: npm test
            - run: npx tsc

    # publish-github-release:
    #     docker:
    #       - image: gcr.io/snyk-technical-services/cicd-github
    #         auth:
    #           username: _json_key
    #           password: $GCLOUD_GCR_SNYK_TS_READER
    #     steps:
    #       - checkout
    #       - attach_workspace:
    #           at: .
    #       - run:
    #           name: "Publish Release on GitHub"
    #           command: |    
    #             # VERSIONJUMP=$(git log --oneline -1 --pretty=%B | cat | grep -E 'minor|major|patch' | awk -F ':' '{print $1}')   
    #             # VERSION=$(/workdir/nextver.sh "$VERSIONJUMP")
    #             VERSION=$(cat /root/project/dist/package.json | grep version | awk {'print $2'} | sed 's/"//g' | sed 's/,//g')
    #             cd /root/project/dist/binaries
    #             sha256sum snyk-delta-linux > snyk-delta-linux.sha256 && sha256sum snyk-delta-macos > snyk-delta-macos.sha256 && sha256sum snyk-delta-win.exe > snyk-delta-win.exe.sha256
    #             cd -
    #             ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} dist/binaries
workflows:
    version: 2.1
    nightly:
        triggers:
          - schedule:
              cron: "0 0 * * *"
              filters:
                branches:
                  only:
                    - master
        jobs:
            - build-test-monitor:
                context: SNYK

    build-test-monitor:
        jobs:
            - build-test-monitor:
                context: SNYK
                filters:
                    branches:
                        only:
                            - master
            # - publish-github-release:
            #     context: SNYK
            #     requires:
            #         - build-test-monitor
            #     filters:
            #         branches:
            #           only:
            #             - master
    build-test:
        jobs:
            - build-test:
                context: SNYK
                filters:
                    branches:
                        ignore:
                        - master
                        - /pull\/[0-9]+/
            - build-test-from-fork:
                filters:
                    branches:
                        only:
                        - /pull\/[0-9]+/
