version: 2.1
orbs:
    snyk: snyk/snyk@0.0.8
jobs:
    build-test-publish:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install semantic-release @semantic-release/exec pkg --save-dev
            - run: npm install
            - run: npm test
            - snyk/scan:
                fail-on-issues: true
                monitor-on-build: true
                token-variable: SNYK_TOKEN
            - run: npx semantic-release
    build-test:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install
            - run: npm test
            - snyk/scan:
                fail-on-issues: true
                monitor-on-build: false
                token-variable: SNYK_TOKEN
            - run: npx tsc
            - snyk/scan:
                fail-on-issues: false
                monitor-on-build: false
                token-variable: SNYK_TOKEN
                additional-arguments: --json-file-output=snykTestResults.json

            - run: npx snyk-prevent-gh-commit-status ./snykTestResults.json ${GITHUB_TOKEN} ${CIRCLE_PROJECT_USERNAME} ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_SHA1} ${CIRCLE_PULL_REQUEST} ${CIRCLE_BUILD_URL}
    build-test-from-fork:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install
            - run: npm test
            - run: npx tsc

workflows:
    version: 2.1
    nightly:
        triggers:
          - schedule:
              cron: "0 0 * * *"
              filters:
                branches:
                  only:
                    - master
        jobs:
            - build-test-publish:
                context: SNYK

    build-test-publish:
        jobs:
            - build-test-publish:
                context: SNYK
                filters:
                    branches:
                        only:
                            - master
    build-test:
        jobs:
            - build-test:
                context: SNYK
                filters:
                    branches:
                        ignore:
                        - master
                        - /pull\/[0-9]+/
            - build-test-from-fork:
                filters:
                    branches:
                        only:
                        - /pull\/[0-9]+/
